Start of workshop
pyladiesams/conformal-prediction-jan2024 pull request #1
Opened 2023-12-22 08:56 UTC by ingevandenende

First solution file and presentation added.

2024-01-07 21:13 UTC, nancyirisarri requested changes
Hi,

Nice slides. I think they are very clear and well divided. The notebooks are also interesting. I have not checked them fully, but there seems to be missing notebooks in the _workshop_ folder. We usually separate unfinished or incomplete notebooks in the _workshop_ folder, and include the completed ones in the _solutions_ folder. During the session, the participants will work on completing the notebooks. Is this also your intention?

Also, it is a small detail, can you please try to commit the notebooks without the output of running the cells?

You could also consider providing instructions on adding the virtual environment as a kernel, something like these [https://janakiev.com/blog/jupyter-virtual-envs/](https://janakiev.com/blog/jupyter-virtual-envs/).

2024-01-07 21:13 UTC, nancyirisarri commented on README.md
> +### Presentation: [Conformal prediction](workshop/2024-01 PyLadies Amsterdam meet-up - Inge - Conformal prediction.pdf)
Hi, is this link working for you? I do not get it as a link.

2024-01-16 08:12 UTC, ingevandenende commented on README.md
> +### Presentation: [Conformal prediction](workshop/2024-01 PyLadies Amsterdam meet-up - Inge - Conformal prediction.pdf)
No, for me it is not working either. I just copied the name of the presentation into the template. How can I change it to a link?

2024-01-16 08:14 UTC, ingevandenende commented
Thank you. Yes, my plan is to first finalize the solution file and after that create the workshop files to prevent double work. Do you have feedback on the code in the solution files?

I will update the notebooks to hide the output.

2024-01-23 15:37 UTC, merged